### ISSUE TITLE
template:'view/airview/demo-1.html' external html page not load

### ISSUE THREAD

**Issue by rahuldmk** [sebelga/ionic-advanced-carousel#4]
vm.carouselOptions4 = {
            carouselId:'carousel-4',
            align:'left',
            selectFirst:true,
            centerOnSelect:true,
            template:'view/airview/demo-1.html'
 };

how to set template url link in controller

ionic.bundle.js:23826 GET http://localhost:8100/view/airview/demo-1.html 404 (Not Found)(anonymous function) @ ionic.bundle.js:23826sendReq @ ionic.bundle.js:23645serverRequest @ ionic.bundle.js:23357processQueue @ ionic.bundle.js:27879(anonymous function) @ ionic.bundle.js:27895Scope.$eval @ ionic.bundle.js:29158Scope.$digest @ ionic.bundle.js:28969Scope.$apply @ ionic.bundle.js:29263done @ ionic.bundle.js:23676completeRequest @ ionic.bundle.js:23848requestLoaded @ ionic.bundle.js:23789
ionic.bundle.js:25642 Error: [$compile:tpload] Failed to load template: ../view/airview/demo-1.html (HTTP status: 404 Not Found)
http://errors.angularjs.org/1.4.3/$compile/tpload?p0=..%2Fview%2Fairview%2Fdemo-1.html&p1=404&p2=Not%20Found

**Comment by loixlab** [comment]
Hi,
Could you double check that the template exists in your browser going to:
'http://localhost:8100/view/airview/demo-1.html'
It seems that it does not exist at that direction (404).

**Comment by loixlab** [comment]
I am closing this issue. Feel free to contact me again if the problem persists.
