### ISSUE TITLE
Items on new line

### ISSUE THREAD

**Issue by bknill** [sebelga/ionic-advanced-carousel#5]
Hi - great little carousel! 

I've got it working but a items are getting pushed onto a new line in my app, if I add 20 from the createArray function it's around 18-20 that go on a new line, if I use my own data and add the items after they've loaded it's around half that go onto a new line. 

I'm using this within a tab so I'm not sure if that has any bearing?

**Comment by bknill** [comment]
A  $scope.$apply(); after the  $scope.$broadcast('a-carousel.arrayupdated', 'carousel-1'); seems to have fixed it interrmittedly

**Comment by bknill** [comment]
OK I've fixed this by using the demo 1 example. Must be something to do with measuring the width when using the text directive.

**Comment by loixlab** [comment]
Hi, great you found the solution. I was going to say that it seemed like a CSS problem on your wrapper.
